export const skillsData = [
  { name: "HTML", icon: "/images/skills/html5.svg" },
  { name: "CSS", icon: "/images/skills/css.svg" },
  { name: "Sass", icon: "/images/skills/sass.svg" },
  { name: "Bootstrap", icon: "/images/skills/bootstrap.svg" },
  { name: "Material", icon: "/images/skills/material.svg" },
  { name: "TailwindCSS", icon: "/images/skills/tailwind-css.svg" },
  { name: "GSAP", icon: "/images/skills/gsap.svg" },
  { name: "JavaScript", icon: "/images/skills/javascript.svg" },
  { name: "React", icon: "/images/skills/react.svg" },
  { name: "NextJS", icon: "/images/skills/nextjs.svg" },
  { name: "Node", icon: "/images/skills/nodejs.svg" },
  { name: "Wordpress", icon: "/images/skills/wordpress.png" },
  { name: "Jest", icon: "/images/skills/jest-icon.svg" },
  { name: "MongoDB", icon: "/images/skills/mongoDB.svg" },
  { name: "Sanity", icon: "/images/skills/sanity-seeklogo.com.svg" },
  { name: "Stripe", icon: "/images/skills/stripe-4.svg" },
  { name: "GraphQL", icon: "/images/skills/graphql.svg" },
  { name: "Shopify", icon: "/images/skills/shopify.svg" },
  { name: "Strapi", icon: "/images/skills/strapi.svg" },
  { name: "AWS S3", icon: "/images/skills/aws-s3.svg" },
  { name: "PostgreSQL", icon: "/images/skills/postgresql.svg" },
  { name: "Firebase", icon: "/images/skills/firebase.svg" },
  { name: "SQL", icon: "/images/skills/sql.png" },
];
